### ISSUE TITLE
Create a readme

### ISSUE THREAD

**Issue by dan1994** [dan1994/pyzshcomplete#1]

**Comment by anntzer** [comment]
I didn't want to spam the tracker with pointless new issues so am just commenting here: This project looks great, thanks a lot for finally providing zsh users with a replacement for argcomplete :)

**Comment by dan1994** [comment]
Thanks @anntzer!
I'm really glad to hear that my project is useful to other people, especially since this is my first open source project.
I hope to make it even better soon, and provide more meaningful completions!
