### ISSUE TITLE
How to write ZSH completion function in Python

### ISSUE THREAD

**Issue by blueray453** [dan1994/pyzshcomplete#48]
I am getting started with this project so I apologize for such a basic question.

For example the following is a zsh completion function for command `foo`:

```
#compdef _foo foo
compadd first second third fourth
```

So, if we type `foo <tab>` in the zsh terminal, it suggests first second third fourth.

How can I do this using pyzshcomplete?

**Comment by dan1994** [comment]
The idea of pyzshcomplete is that you shouldn't have to know how to write zsh completion scripts at all. Rather, it determines which arguments should be completed for your script based on the argument parser defined in the script.

I suggest you read the project's readme and try out a simple example. If you still have questions, feel free to ask.

Note that a prerequisite is that you use python's built-in argparse library, as it is the only one supported by pyzshcomplete.

**Comment by blueray453** [comment]
Thank you very much for this kind reply.
