### ISSUE TITLE
print out python_argcomplete_scan_head_noerr in first attempt

### ISSUE THREAD

**Issue by eaybek** [dan1994/pyzshcomplete#60]
> ./test.py __pyzshcomplete_scan_python_script_for_magic:3: command not found: __python_argcomplete_scan_head_noerr

first of all cool project!!! congrats

and as an issue or bug maybe
its print out that error when zsh first open after second completion try its work as expected but first attempt is buggy
![Screenshot from 2021-07-16 22-24-40](https://user-images.githubusercontent.com/6156441/125999475-fe3c46bb-0a54-41c4-bf3a-82ba577c9e7b.png)

**Comment by marble** [comment]
Confirmed!

**Comment by dan1994** [comment]
Thanks for opening an issue and sorry for the long wait.
I looked into this and found the problem. Should fix it soon!
